version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "AtlassianPS/AtlassianPS.Standards*"
    labels:
      - dependencies
      - github_actions
      - "release:none"
    commit-message:
      prefix: "⬆️ "
