# https://www.appveyor.com/docs/appveyor-yml/
# https://www.yamllint.com

# Before adding this, the following error showed up:
# "Specify a project or solution file. The directory does not contain a project or solution file."
build: off

# Ignore testing a commit if only the readme changed
skip_commits:
  files:
    - README.md
  message: /skip\-tests/

# Need my PS Gallery API key if publishing a module update
# The "secure:" value is the Appveyor encryption of the key
environment:
  PSGalleryAPIKey:
    secure: 1wcOLpXblYir1QP8rYSusYG9D216kqXfs/FqDft4/9ISWaYD/ne/YP0mN5qeA0G+

# Install NuGet to grab modules from the PowerShell Gallery
install:
- ps: |
    Install-PackageProvider -Name NuGet -Force
    Install-Module -Name Pester -Force
  
# Offload all PowerShell test/build work to a separate file
test_script:
  - ps: . .\build.ps1

# Post in my Slack #builds channel
# The "secure:" value is the Appveyor encryption of my Slack API "test" token
notifications:
  - provider: Slack
    auth_token:
      secure: +Y/c3bM0RNleCHnyAo+QHxn7PqTfaQdfHoh6Ki6ZMTsF8Aut5/ND1GIIb8cVwuahNj77QKyLCFvHNx0Yx9F12g==
    channel: '#builds'
